config/routes.rb
Urbanbook::Application.routes.draw do
  get "tag/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :people
  resources :tag
  
  devise_for :users
  root "people#index"
  get 'tagged' => 'people#tagged', :as => 'tagged'
  get 'admin' => 'admin#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :user
	has_paper_trail
	acts_as_taggable

	def admin_permalink
    admin_post_path(self)
    end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_tagger

  has_many :person

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :tag_cloud

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @versions = @person.versions #Use if want to get @versions.count
 
    @last_change = @person.versions.last
    @id_who_made_the_change = (User.find(@last_change.whodunnit.to_i).id if @last_change && @last_change.whodunnit) || nil

  end

  def tag_cloud
    @tags = Tag.all.order('count desc').limit(20)
  end

  def tagged
    if params[:tag].present? 
      @people = Person.tagged_with(params[:tag])
    else 
      @people = Person.all
    end  
  end

  # GET /people/new
  def new
    @person = current_user.person.build
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = current_user.person.build(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :twitter, :facebook, :instagram, :vine, :tag_list )
    end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def show
  @tag = Tag.find(params[:id])
  @people = Person.tagged_with(@tag.name)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">UrbanBook</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
<ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "People", people_path %></li>

        <% if user_signed_in? %>
        <li>Current ID: <%= current_user.id %> </li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_version.html.erb
<% if !@versions.empty? %>
  <h3>Current Version: <%= @versions.length %></h3>

  <b>Created At:</b>
  <%= @versions.last.created_at%>
  <br>
  <b>User</b>: <%= User.find(@versions.last.whodunnit).email %>
  <br>
  <% if @versions.length.to_i > 1 %>
    <% if params[:version].to_i > 1 || !params[:version] %>
      <%= link_to "Previous version", {:version => (params[:version] || @versions.length).to_i - 1}%>
      <br>
    <% end %>
    <% if params[:version] %>
      <h3>This is <%= "#{params[:version]}"%> version</h3>

      <b>Modify at:</b>
      <%= @versions[(params[:version].to_i - 1)].created_at %>
      <br>
      <b>User</b>:
      <%= User.find(@versions[(params[:version].to_i - 1)].whodunnit).email %>
      <br>

      <%= link_to "Go to current version"%>
    <% end %>
  <% end %>
<% else %>
  <p>This item does not have any registered version.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urbanbook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
     <%= yield %>
   </div>


</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br>
    <%= f.text_field :twitter %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :instagram %><br>
    <%= f.text_field :instagram %>
  </div>
  <div class="field">
    <%= f.label :vine %><br>
    <%= f.text_field :vine %>
  </div>

<div class="field">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<h2>Tag Cloud</h2>
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
  <%= link_to tag.name, tag_path(tag), :class => css_class %>
<% end %>


<br/>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Twitter</th>
      <th>Facebook</th>
      <th>Instagram</th>
      <th>Vine</th>
      <th>Created By User ID</th>
      <th>Tags</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.twitter %></td>
        <td><%= person.facebook %></td>
        <td><%= person.instagram %></td>
        <td><%= person.vine %></td>
        <td><%= person.user_id %></td>
        <td><%= person.tag_list %></td>

        <td><%= link_to 'Show', person %></td>

        <!-- Show Edit/Delete only to Logged In Users -->
        <% if current_user %>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Person', new_person_path %>
<% end %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<!-- If there's a nil error then it's the first creation -->
 <% if @last_change && @last_change.whodunnit || nil %>
        <strong>Last Update by User ID:</strong> <%= @id_who_made_the_change %> 
      <% else %> 
        <strong>First Creation By User ID:</strong> <%= @person.user_id %>
       <% end %>

<p>
  <h2>Tags:</h2>

<% @person.tags.any? %> 
  <% @person.tags.each do |tag| %> 
    <%= link_to tag.name, tag_path(tag) %>
 <% end %>
</p>

<hr>
<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @person.twitter %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @person.facebook %>
</p>

<p>
  <strong>Instagram:</strong>
  <%= @person.instagram %>
</p>

<p>
  <strong>Vine:</strong>
  <%= @person.vine %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/tag/show.html.erb
<h1>Tag#show</h1>
<p>Find me in app/views/tag/show.html.erb</p>


<h1>People Tagged as <%= @tag.name %></h1>

<% if @people.count > 0 %>

  <ul>

  <% @people.each do |person| %>

    <li><%= link_to person.name, person_path(person) %></li>

  <% end %>

  </ul>

<% else %>

  <p>This tag is not associated with any people.</p>

<% end %>